### ISSUE TITLE
Error NMapsMap 3.3.0

### ISSUE THREAD

**Issue by ElonPark** [navermaps/ios-map-sdk#1]
SDK를 3.3.0으로 업데이트한 이후로 에러가 발생 합니다.
비트코드를 적용하셨다는 이슈에 답변을 보고 제 앱 타겟에 비트코드를 적용해도 똑같은 에러가 발생 합니다.

![스크린샷 2019-04-17 오전 1 22 03](https://user-images.githubusercontent.com/13270453/56227201-df18d280-60af-11e9-96f1-c4af688cf72e.png)

개발자 커뮤니티에서도 동일한 에러가 발생한다는 분이 계셨습니다.

현재는 pod에서 강제로 3.2.1버전으로 다운그레이드하여 사용 중 입니다.

**Comment by garoad** [comment]
@ElonPark 
SDK 3.3.0 버전 부터 비트코드 적용으로 용량이 늘어나서 git-lfs를 적용하게 되었습니다. [git-lfs](https://git-lfs.github.com/)를 설치하시고 현재 설치된 Pods/ 폴더와 pod cache clean NMapsMap 명령어로 캐시를 삭제 하신후 다시 업데이트 해보시기 바랍니다.

**Comment by ElonPark** [comment]
이미 해놨지만 동일합니다.

**Comment by garoad** [comment]
@ElonPark 
해당 에러메세지는 git-lfs 정보 파일만 받아와서 정상적으로 동작하지 않는 겁니다. 이전에 받은 캐시가 남아있으면 git-lfs가 정상 동작하지 않으므로 cocoapods 캐시를 다 날리고 해야합니다. 이번에 배포된 3.3.0 바이너리 크기는 198MB 정도 되므로 이 크기가 아니라면 캐시 삭제 및 프로젝트 클린을 다시한번 해보시길 바랍니다.

**Comment by ElonPark** [comment]
맥에는 git-lfs는 설치되어있는데 프로젝트 폴더에서 
`$ git-lfs install` 없이 진행해서 그렇군요.

감사합니다.

---
일반적인 경우에는 아래처럼 하면 될거 같습니다.

```shell
#실행 단계

#git-lfs가 설치 안된 경우 설치
$ brew install git-lfs

#프로젝트 폴더로 이동
$ cd ~/${project_parh}
#프로젝트 폴더에서 git-lfs 설치
$ git-lfs install
#pod 캐시 제거
$ pod cache clean NMapsMap
# SDK 업데이트
$ pod update NMapsMap
```
진행 후 Xcode에서 프로젝트 클린 후 빌드
