### ISSUE TITLE
[질문] 마커 클러스터링 관련 문의

### ISSUE THREAD

**Issue by ElonPark** [navermaps/ios-map-sdk#2]
네이버 js버전 지도에서는 마커 클러스터링 예제를 공개하고 있는걸로 알고 있는데,
혹시 구글맵처럼 SDK나 오픈소스로 마커 클러스터링을 지원하실 여부가 있는지 궁금 합니다.

**Comment by garoad** [comment]
@ElonPark 
  안녕하세요 마커 클러스터링은 아직 지원예정이 없습니다. 
다른 오픈소스를 사용하여 구현하시기 바랍니다. 
감사합니다.
