### ISSUE TITLE
"_OBJC_CLASS_$_NMFMapView", referenced from symbol(s) not found for architecture arm64

### ISSUE THREAD

**Issue by sohutek** [navermaps/ios-map-sdk#3]
Hi, plz tell me what's wrong here. I can't find any solution to make it work
![Ảnh chụp Màn hình 2019-07-01 lúc 3 47 20 CH](https://user-images.githubusercontent.com/39855228/60423074-8c16dc00-9c17-11e9-9ef1-627f80f421d1.png)

**Comment by garoad** [comment]
@sohutek 
Hi, I don't know what is problem above messages. Can you show more detail log or sample code.

**Comment by sohutek** [comment]
Uhm. Maybe i think the problem is this library doesn't support 64-bit real iphone machines. That's right?

**Comment by garoad** [comment]
We support all architectures. Can you check this issue problem about git-lfs?
https://github.com/navermaps/ios-map-sdk/issues/1

**Comment by sohutek** [comment]
Ok thanks. I got it. Thanks so much
