### ISSUE TITLE
Can i set markers as drag and drop and listen for this changing action

### ISSUE THREAD

**Issue by sohutek** [navermaps/ios-map-sdk#4]
In version 2 we can make it easy like this. 
***.setPOIflagMode(.drag);
And set listener for that via
open func onMapOverlay(_ poiDataOverlay: NMapPOIdataOverlay!, didChangePOIitemLocationTo location: NGeoPoint, withType poiFlagType: NMapPOIflagType) {}

How can i do that in version 3?

**Comment by garoad** [comment]
Sorry we are not support drag mode in version 3.
