### ISSUE TITLE
Hi, I get the request timed out with error code -1001. My internet is still good

### ISSUE THREAD

**Issue by shiphaniran** [navermaps/ios-map-sdk#5]
<img width="413" alt="Screen Shot 2019-07-05 at 1 34 25 PM" src="https://user-images.githubusercontent.com/20613721/60702680-cb03a500-9f29-11e9-9c5f-37eb68ac049e.png">

**Comment by garoad** [comment]
Hi, did you insert clientkey? read these guides.
https://navermaps.github.io/ios-map-sdk/guide-en/1.html
https://docs.ncloud.com/en/naveropenapi_v3/application.html

**Comment by shiphaniran** [comment]
Yes, I've already insert client key

**Comment by garoad** [comment]
Ok, then check your app bundleId of registered clientId?
Registered 1 bundleId only active 1 clientId.

**Comment by shiphaniran** [comment]
<img width="505" alt="Screen Shot 2019-07-05 at 4 31 47 PM" src="https://user-images.githubusercontent.com/20613721/60713014-69036980-9f42-11e9-8f6a-51625b2f3d7a.png">
Hi, need to remove one in iOS bundle Id. right?

**Comment by garoad** [comment]
Hmm, I think it's server issue. Could you report isssue to this link?
https://www.ncloud.com/mypage/myquestion/all

**Comment by sohutek** [comment]
@garoad To anybody who uses "Timberjack" to catch HTTP log, please be cautious of encountering this issue with MaverMaps. Remove it helping you a lot.
