### ISSUE TITLE
NMapsMap git lfs적용 불가

### ISSUE THREAD

**Issue by JakyungYoon** [navermaps/ios-map-sdk#6]
<img width="772" alt="Screen Shot 2019-07-21 at 2 28 38 PM" src="https://user-images.githubusercontent.com/28960688/61587353-df9b9a80-abc3-11e9-8cec-c630cbad5c78.png">

git lfs를 다운하는 과정에서 문제가 발생이 하였습니다.. 
pod cache clean NMapsMap를 하면 NMapsMap이 없다고 뜨며 적용을 할려고하면 이러한 문제가 생깁니다. 어떻게 해결을 해야하나요?

**Comment by garoad** [comment]
안녕하세요 고객문의는 네이버클라우드플랫폼을 통해 접수 받고 있습니다.
https://www.ncloud.com/mypage/myquestion/all
다음 링크를 통해 문의해주시면 됩니다.
감사합니다.
