### ISSUE TITLE
How can i move Camera to show all pin fit the map?

### ISSUE THREAD

**Issue by sohutek** [navermaps/ios-map-sdk#7]
Ohm. Maybe what i got is just move Camera to only one pin or coordinate, but i can't find any functions to show all pin fit to the map. Please tell me how i can do it

**Comment by garoad** [comment]
Hello, we received issues from Naver Cloud Platform.
Please leave issue follow link.
https://www.ncloud.com/mypage/myquestion/all
Thank you.
